title: Chunlei Ge # your name (or website title) here
logo: "/images/Picture2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
I am a Ph.D. candidate in Statistics with extensive experience as a Graduate Research Assistant, demonstrating a strong background in statistical research. 
I have also served as a Graduate Teaching Assistant, teaching Math, Statistics, and Data courses over the past few years. 
I am skilled in statistical modeling, data analysis, research, teaching, and education. 
My academic background includes a Master of Arts in Statistics from York University, 
and I am currently pursuing a Ph.D. in Mathematics with a focus on Statistics at UBC.
  <br><br>
  <a href="https://www.linkedin.com/in/chunlei-ge-40741969/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
